// @vitest-environment node

/**
 * Reversing a blob key to the thing that owns it.
 *
 * Against a real PGlite, like every other suite here, because the two claims
 * worth making are that the join finds the channel's owner and that it does so
 * in *one* statement. A mock could only restate the implementation, and the
 * statement count is the half that the returned data cannot reveal.
 */

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import type { SqlExecutor, SqlRow } from "@/adapters/db/driver";
import {
  MEDIA_ACCESS_CACHE_TTL_MS,
  createMediaAccessRepository,
  mediaOwnerFromKey,
  resetMediaAccessCacheForTests,
} from "@/adapters/repositories/media-access";
import { createVideo } from "@/adapters/repositories/videos";
import type { Channel, User } from "@/domain/types";

import {
  countingExecutor,
  createTestChannel,
  createTestUser,
  setupTestDatabase,
} from "./harness";

const t = setupTestDatabase();

let owner: User;
let channel: Channel;

beforeEach(async () => {
  resetMediaAccessCacheForTests();
  owner = await createTestUser(t.db);
  channel = await createTestChannel(t.db, { ownerId: owner.id });
});

afterEach(() => {
  vi.restoreAllMocks();
});

function repository(exec: SqlExecutor = t.db) {
  return createMediaAccessRepository(exec);
}

/* ============================================================== parsing == */

describe("mediaOwnerFromKey", () => {
  it.each([
    ["a media segment", "videos/abc123/720p/seg-00001.m4s"],
    ["an init segment", "videos/abc123/720p/init.mp4"],
    ["a master playlist", "videos/abc123/master.m3u8"],
    ["the progressive source", "videos/abc123/source.mp4"],
    ["a thumbnail", "videos/abc123/thumb-hq.jpg"],
    ["a caption track", "videos/abc123/captions-en.vtt"],
  ])("reads the video id out of %s", (_label, key) => {
    expect(mediaOwnerFromKey(key)).toEqual({
      kind: "video",
      videoId: "abc123",
    });
  });

  it.each([
    ["an avatar", "channels/ch_1/avatar.jpg"],
    ["a banner", "channels/ch_1/banner.jpg"],
  ])("reads the channel id out of %s", (_label, key) => {
    expect(mediaOwnerFromKey(key)).toEqual({
      kind: "channel",
      channelId: "ch_1",
    });
  });

  /**
   * The fall-through the whole function exists to avoid. A key that matches no
   * shape this app writes has no owner, and "no owner" must mean refused
   * rather than "no rule applied, so serve it".
   */
  it.each([
    ["a namespace this app does not own", "secrets/keys.json"],
    ["an ad creative, which has no shape here yet", "ads/creative-1.mp4"],
    ["a prefix with no tail", "videos/abc123/"],
    ["a prefix and nothing else", "videos/abc123"],
    ["the namespace alone", "videos"],
    ["a bare filename", "source.mp4"],
    ["an empty key", ""],
    ["a leading slash", "/videos/abc123/source.mp4"],
    ["an empty id", "videos//source.mp4"],
    ["a traversal in the id", "videos/../source.mp4"],
    ["a traversal in the tail", "videos/abc123/../../etc/passwd"],
    ["a dot segment in the tail", "videos/abc123/./secrets"],
    ["the wrong case of a namespace", "Videos/abc123/source.mp4"],
    ["a plural nobody writes", "video/abc123/source.mp4"],
  ])("refuses %s", (_label, key) => {
    expect(mediaOwnerFromKey(key)).toBeNull();
  });

  /**
   * Ids are generated by `newVideoId` (nanoid, `A-Za-z0-9_-`) and by `newId`
   * (`prefix_base64url`), so the accepted character class has to cover both
   * and nothing wider — a `.` in the id position would let `videos/../x` past
   * a lazier pattern.
   */
  it("accepts every character an id generator can produce", () => {
    expect(mediaOwnerFromKey("videos/aB0_-zZ9/source.mp4")).toEqual({
      kind: "video",
      videoId: "aB0_-zZ9",
    });
    expect(mediaOwnerFromKey("channels/ch_aB0_-zZ9/avatar.jpg")).toEqual({
      kind: "channel",
      channelId: "ch_aB0_-zZ9",
    });
  });

  it("refuses an id with a character no generator produces", () => {
    expect(mediaOwnerFromKey("videos/ab.c/source.mp4")).toBeNull();
  });
});

/* ========================================================== resolution == */

describe("subjectForKey", () => {
  it.each(["public", "unlisted", "private"] as const)(
    "reports a %s video's visibility and its channel's owner",
    async (visibility) => {
      const video = await createVideo(t.db, {
        id: `vid-${visibility}`,
        channelId: channel.id,
        title: visibility,
        visibility,
      });

      const subject = await repository().subjectForKey(
        `videos/${video.id}/720p/seg-00001.m4s`,
      );
      expect(subject).toEqual({
        kind: "video",
        videoId: video.id,
        channelId: channel.id,
        ownerId: owner.id,
        visibility,
      });
    },
  );

  it("reports a channel's owner, and treats its assets as public", async () => {
    const subject = await repository().subjectForKey(
      `channels/${channel.id}/avatar.jpg`,
    );
    expect(subject).toEqual({
      kind: "channel",
      channelId: channel.id,
      ownerId: owner.id,
      visibility: "public",
    });
  });

  it("is null for a video id with no row", async () => {
    expect(
      await repository().subjectForKey("videos/nosuchvideo/source.mp4"),
    ).toBeNull();
  });

  it("is null for a channel id with no row", async () => {
    expect(
      await repository().subjectForKey("channels/nosuchchannel/avatar.jpg"),
    ).toBeNull();
  });

  it("is null for a key that matches no known shape", async () => {
    expect(await repository().subjectForKey("secrets/keys.json")).toBeNull();
  });

  /**
   * `videos → channels` is a join, not two reads. The count is the assertion:
   * nothing about the returned subject would reveal a second round trip, and
   * this lookup sits on a path a player hits every couple of seconds.
   */
  it("resolves a video and its owner in one statement", async () => {
    const video = await createVideo(t.db, {
      id: "vid-onestmt",
      channelId: channel.id,
      title: "one",
    });
    const counting = countingExecutor(t.db);

    await repository(counting).subjectForKey(`videos/${video.id}/source.mp4`);
    expect(counting.statements).toHaveLength(1);
  });

  it("costs nothing at all for a key it cannot parse", async () => {
    const counting = countingExecutor(t.db);
    await repository(counting).subjectForKey("secrets/keys.json");
    expect(counting.statements).toHaveLength(0);
  });

  /**
   * Fail closed. The `check` constraint on `videos.visibility` makes this
   * unreachable through the application, but this is the one place the column
   * is a security decision rather than a display value, and an unrecognised
   * value must deny rather than fall through to "not private, therefore
   * servable".
   */
  it("treats an unrecognised visibility as private", async () => {
    // A fake executor rather than DDL surgery on the shared schema: the thing
    // under test is a coercion of a driver value, and the row it guards against
    // is one the `check` constraint makes unproducible through the database.
    const row: SqlRow = {
      video_id: "vid-odd",
      channel_id: channel.id,
      owner_id: owner.id,
      visibility: "friends-only",
    };
    const impossible: SqlExecutor = {
      query: async <T extends SqlRow>(): Promise<T[]> => [row as T],
      execute: async () => 0,
    };

    const subject = await repository(impossible).subjectForKey(
      "videos/vid-odd/source.mp4",
    );
    expect(subject?.visibility).toBe("private");
  });
});

/* =============================================================== cache == */

describe("cachedSubjectForKey", () => {
  it("answers the same thing the uncached lookup does", async () => {
    const video = await createVideo(t.db, {
      id: "vid-same",
      channelId: channel.id,
      title: "same",
      visibility: "private",
    });
    const key = `videos/${video.id}/720p/seg-00001.m4s`;

    expect(await repository().cachedSubjectForKey(key)).toEqual(
      await repository().subjectForKey(key),
    );
  });

  /**
   * The reason this exists. A player fetches a segment every two seconds and a
   * view is ~53 requests; one authorisation query per request would be a real
   * per-view cost against Neon, paid on the hot path of every public video.
   */
  it("costs one statement for a whole burst of segment requests", async () => {
    const video = await createVideo(t.db, {
      id: "vid-burst",
      channelId: channel.id,
      title: "burst",
    });
    const counting = countingExecutor(t.db);
    const repo = repository(counting);

    for (let index = 0; index < 20; index += 1) {
      await repo.cachedSubjectForKey(
        `videos/${video.id}/720p/seg-${String(index).padStart(5, "0")}.m4s`,
      );
    }
    expect(counting.statements).toHaveLength(1);
  });

  /**
   * A cold cache and a player opening several connections at once is a
   * thundering herd, and the fix is the one `adapters/db/index.ts` already
   * uses: memoise the in-flight promise rather than the value.
   */
  it("collapses concurrent misses into one statement", async () => {
    const video = await createVideo(t.db, {
      id: "vid-herd",
      channelId: channel.id,
      title: "herd",
    });
    const counting = countingExecutor(t.db);
    const repo = repository(counting);

    await Promise.all(
      Array.from({ length: 8 }, (_, index) =>
        repo.cachedSubjectForKey(`videos/${video.id}/720p/seg-0000${index}.m4s`),
      ),
    );
    expect(counting.statements).toHaveLength(1);
  });

  /**
   * Negative results are cached too. Without that, a walk over guessed ids is
   * an unthrottled query per request — the cheapest denial of service in the
   * application, aimed at the one path that is already the hottest.
   */
  it("caches the absence of a row", async () => {
    const counting = countingExecutor(t.db);
    const repo = repository(counting);

    expect(await repo.cachedSubjectForKey("videos/ghost/source.mp4")).toBeNull();
    expect(await repo.cachedSubjectForKey("videos/ghost/720p/init.mp4")).toBeNull();
    expect(counting.statements).toHaveLength(1);
  });

  /**
   * The cost of the cache, asserted rather than described: a video made
   * private goes on being served for up to one TTL. That is the trade the TTL
   * is short for, and stating it as a test is the only way it stays a known
   * trade rather than a surprise.
   */
  it("serves a stale permit for at most one TTL", async () => {
    const video = await createVideo(t.db, {
      id: "vid-stale",
      channelId: channel.id,
      title: "stale",
    });
    const key = `videos/${video.id}/source.mp4`;
    const repo = repository();

    expect((await repo.cachedSubjectForKey(key))?.visibility).toBe("public");
    await t.db.execute("update videos set visibility = 'private' where id = $1", [
      video.id,
    ]);
    expect((await repo.cachedSubjectForKey(key))?.visibility).toBe("public");

    // `Date.now` rather than fake timers: PGlite's WASM loader schedules real
    // work, and replacing the timer functions underneath it stalls the query
    // this test is about.
    const base = Date.now();
    vi.spyOn(Date, "now").mockReturnValue(base + MEDIA_ACCESS_CACHE_TTL_MS + 1);
    expect((await repo.cachedSubjectForKey(key))?.visibility).toBe("private");
  });

  it("is short enough to be a window rather than a policy", () => {
    expect(MEDIA_ACCESS_CACHE_TTL_MS).toBeLessThanOrEqual(30_000);
  });

  /**
   * A failed lookup must not occupy the slot: the next request should try
   * again rather than inherit a transient database error for the rest of the
   * window.
   */
  it("does not cache a lookup that threw", async () => {
    const video = await createVideo(t.db, {
      id: "vid-throw",
      channelId: channel.id,
      title: "throw",
    });
    const key = `videos/${video.id}/source.mp4`;

    let fail = true;
    const flaky: SqlExecutor = {
      query: async (sql, params) => {
        if (fail) {
          fail = false;
          throw new Error("connection reset");
        }
        return t.db.query(sql, params);
      },
      execute: (sql, params) => t.db.execute(sql, params),
    };

    await expect(repository(flaky).cachedSubjectForKey(key)).rejects.toThrow(
      "connection reset",
    );
    expect(await repository(flaky).cachedSubjectForKey(key)).toMatchObject({
      kind: "video",
      videoId: video.id,
    });
  });

  it("does not confuse a video id with a channel id of the same text", async () => {
    await createVideo(t.db, {
      id: "collide",
      channelId: channel.id,
      title: "collide",
      visibility: "private",
    });
    await t.db.execute(
      `insert into channels (id, owner_id, handle, name)
       values ('collide', $1, 'collide', 'Collide')`,
      [owner.id],
    );
    const repo = repository();

    expect((await repo.cachedSubjectForKey("videos/collide/source.mp4"))?.kind).toBe(
      "video",
    );
    expect(
      (await repo.cachedSubjectForKey("channels/collide/avatar.jpg"))?.kind,
    ).toBe("channel");
  });
});
