/**
 * Driving headless Chromium to encode the corpus.
 *
 * The seed corpus cannot live in git — a rendition ladder for two dozen clips is
 * tens of megabytes of binary that changes whenever the encoder does — so it is
 * generated. And it is generated by running the *real* pipeline rather than by
 * writing fixtures, because a fixture layer that bypassed
 * `src/media/encode` would let the encode path rot with nothing failing:
 * `pnpm dev` would still boot into a full library assembled by code nobody was
 * exercising. Seeding therefore *is* an integration test of the transcoder, the
 * muxer and the packager, and it fails loudly when any of them breaks.
 *
 * `VideoEncoder` only exists in a browser, so this file's whole job is to put
 * one there:
 *
 *  1. Serve the project's own TypeScript over `http://127.0.0.1`, transpiled per
 *     request. **The origin is the load-bearing part** — research/01 §4.1 found
 *     `VideoEncoder` silently absent on an un-navigated page in every mode
 *     including fully headed, because WebCodecs requires a secure context and
 *     `about:blank` is not one. `127.0.0.1` is a potentially-trustworthy origin
 *     and fixes it with no flags.
 *  2. Launch Chromium with **no extra arguments**. research/01 §4.3 measured
 *     software AVC encode working headless with zero flags, and
 *     `hardwareAcceleration: "no-preference"` in `capabilities.ts` is what keeps
 *     that true — `prefer-hardware` returns `false` in default headless and then
 *     closes the codec. `--enable-gpu` would reach the hardware encoder (§4.4)
 *     and is deliberately not passed: it makes the run depend on the GPU the
 *     machine happens to have, and a seed corpus that differs between two
 *     machines is worse than a slower one.
 *  3. Call into the page once per clip and unpack what comes back.
 *
 * **Verified on macOS (Apple Silicon), Chromium via Playwright 1.62.1.**
 * research/01 §4.7 is explicit that the Linux case was never run; the
 * software-encode finding should transfer because it is a pure-CPU path
 * unrelated to VAAPI, but that is inference. {@link SeedBrowser.capabilities}
 * exists so a run on another platform *reports* what it found rather than
 * assuming — see the log line the seed script prints.
 *
 * ## No bundler
 *
 * The page imports `@/media/encode/transcode` and gets the actual file. That is
 * a five-line resolver rather than a build step: an import map in `index.html`
 * maps the `@/` prefix onto `/src/`, and the server below answers an
 * extensionless URL by trying `.ts` and then `/index.ts` — which is exactly the
 * resolution `tsconfig.json`'s `moduleResolution: "bundler"` describes. Nothing
 * rewrites a specifier, so what the browser runs is what the repository
 * contains, character for character, minus the type annotations.
 */

import { readFileSync } from "node:fs";
import { createServer, type Server } from "node:http";
import { extname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

import { chromium, type Browser, type Page } from "@playwright/test";
import ts from "typescript";

import type { EncodedSample, LadderRung, TrackConfig } from "@/media/types";

import type { ClipSpec, Palette } from "./corpus";
import type {
  ChannelArtRequest,
  ClipEncodeRequest,
  ClipEncodeResult,
  PosterRequest,
  WireRungOutput,
  WireSegment,
  WireTrack,
} from "./page/main";

/* ============================================================= types == */

export interface EncodedSegment {
  readonly index: number;
  readonly startUs: number;
  readonly durationUs: number;
  readonly samples: readonly EncodedSample[];
}

export interface EncodedRendition {
  readonly rung: LadderRung;
  readonly track: TrackConfig;
  readonly segments: readonly EncodedSegment[];
}

export interface EncodedAudio {
  readonly track: TrackConfig;
  readonly segments: readonly EncodedSegment[];
}

export interface ClipEncoding {
  readonly family: string;
  readonly renditions: readonly EncodedRendition[];
  readonly audio: EncodedAudio | null;
  readonly preview: EncodedRendition;
  readonly posterJpeg: Uint8Array;
  readonly framesDecoded: number;
  readonly elapsedMs: number;
}

export interface ChannelArt {
  readonly avatarJpeg: Uint8Array;
  readonly bannerJpeg: Uint8Array;
}

export interface SeedBrowser {
  /** What this machine's headless Chromium actually reported. Logged, not assumed. */
  capabilities(): Promise<Record<string, unknown>>;
  encodeClip(request: ClipEncodeRequest): Promise<ClipEncoding>;
  renderChannelArt(request: ChannelArtRequest): Promise<ChannelArt>;
  /** A poster with no encode behind it — see the page bridge for why. */
  renderPosterCard(request: PosterRequest): Promise<Uint8Array>;
  close(): Promise<void>;
}

export interface OpenSeedBrowserOptions {
  /** Surfaced so a failing page reports its console rather than timing out. */
  readonly onConsole?: (level: string, text: string) => void;
}

/* ======================================================= module server == */

const PROJECT_ROOT = resolve(fileURLToPath(new URL("../../", import.meta.url)));

/**
 * Which directories the page may read.
 *
 * A short allowlist rather than "anything under the project root": this server
 * is bound to loopback and lives for the length of one seed run, but it is
 * still a process that turns a URL into a file read, and `.env` sits two
 * directories above the code it needs. Nothing outside these two trees is part
 * of the page's module graph.
 */
const SERVABLE_ROOTS = ["src", "scripts"];

const TRANSPILED = new Map<string, string>();

/**
 * TypeScript's own transpiler, per module, cached.
 *
 * `transpileModule` is type-*stripping* with a real parser: no program, no type
 * checking, one file at a time — which is all that is needed, because
 * `pnpm exec tsc --noEmit` has already checked the whole project by the time
 * anyone runs the seed. It handles the syntax Node's built-in stripper cannot
 * (see the note at the top of `scripts/seed.ts`), and `typescript` is already a
 * devDependency, so this adds nothing to `package.json`.
 */
function transpile(path: string): string {
  const cached = TRANSPILED.get(path);
  if (cached !== undefined) return cached;

  const source = readFileSync(path, "utf8");
  const output = ts.transpileModule(source, {
    fileName: path,
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ESNext,
      // Matches `tsconfig.json`. `useDefineForClassFields` is not cosmetic:
      // with it off, a `#private` field initialiser and a declared field
      // initialise in a different order, and `RungEncoder` in `transcode.ts`
      // has both.
      useDefineForClassFields: true,
      inlineSourceMap: true,
      inlineSources: true,
    },
  });
  TRANSPILED.set(path, output.outputText);
  return output.outputText;
}

/** Resolve a URL path to a file, trying the extensions a bundler would. */
function resolveServedPath(urlPath: string): string | null {
  const relative = urlPath.replace(/^\/+/, "");
  const top = relative.split("/")[0] ?? "";
  if (!SERVABLE_ROOTS.includes(top)) return null;

  const base = resolve(join(PROJECT_ROOT, relative));
  if (!base.startsWith(PROJECT_ROOT + sep)) return null;

  for (const candidate of [base, `${base}.ts`, join(base, "index.ts")]) {
    try {
      readFileSync(candidate);
      return candidate;
    } catch {
      /* Try the next shape. */
    }
  }
  return null;
}

function startModuleServer(): Promise<{ server: Server; origin: string }> {
  const indexHtml = resolve(PROJECT_ROOT, "scripts/seed/page/index.html");

  const server = createServer((request, response) => {
    const url = new URL(request.url ?? "/", "http://127.0.0.1");
    const path = url.pathname === "/" ? indexHtml : resolveServedPath(url.pathname);

    if (path === null) {
      response.writeHead(404, { "content-type": "text/plain" });
      response.end(`No servable module at ${url.pathname}`);
      return;
    }

    try {
      if (extname(path) === ".ts") {
        const body = transpile(path);
        response.writeHead(200, {
          "content-type": "text/javascript; charset=utf-8",
          "cache-control": "no-store",
        });
        response.end(body);
        return;
      }
      response.writeHead(200, {
        "content-type": extname(path) === ".html" ? "text/html; charset=utf-8" : "text/plain",
        "cache-control": "no-store",
      });
      response.end(readFileSync(path));
    } catch (error) {
      // A transpile failure has to surface here, not as a blank page: the
      // browser would report only "failed to load module script", which names
      // the URL and not the syntax error.
      response.writeHead(500, { "content-type": "text/plain" });
      response.end(`Failed to serve ${path}: ${String(error)}`);
    }
  });

  return new Promise((resolveServer, rejectServer) => {
    server.once("error", rejectServer);
    // Port 0 asks the kernel for a free one. A fixed port would collide with a
    // second seed run and, worse, with whatever else is listening.
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      if (address === null || typeof address === "string") {
        rejectServer(new Error("The seed module server did not bind to a TCP port."));
        return;
      }
      resolveServer({ server, origin: `http://127.0.0.1:${address.port}/` });
    });
  });
}

/* ============================================================= driver == */

/**
 * Open the encoder page and return a handle to it.
 *
 * The page is opened once for the whole corpus rather than per clip: a Chromium
 * launch is ~300 ms and a page load another ~100 ms, which across two dozen
 * clips is most of a minute spent on process startup. The encoders themselves
 * are constructed and closed per `transcode` call, so nothing leaks between
 * clips — `transcode`'s `finally` disposes every rung unconditionally.
 */
export async function openSeedBrowser(
  options: OpenSeedBrowserOptions = {},
): Promise<SeedBrowser> {
  const { server, origin } = await startModuleServer();

  let browser: Browser | undefined;
  let page: Page | undefined;

  const shutdown = async (): Promise<void> => {
    await browser?.close().catch(() => undefined);
    await new Promise<void>((done) => server.close(() => done()));
  };

  try {
    // No arguments. See the module header: `--enable-gpu` would reach the
    // hardware encoder and make the output depend on the machine.
    browser = await chromium.launch({ headless: true });
    page = await browser.newPage();

    if (options.onConsole) {
      page.on("console", (message) => options.onConsole?.(message.type(), message.text()));
    }
    page.on("pageerror", (error) => {
      options.onConsole?.("pageerror", error.message);
    });

    await page.goto(origin, { waitUntil: "domcontentloaded" });
    // The bridge appears when `main.ts` finishes evaluating; a module that
    // failed to load never sets it, and the timeout below is what turns that
    // into an error naming the page rather than a hang.
    await page.waitForFunction(() => globalThis.__seed !== undefined, undefined, {
      timeout: 30_000,
    });
  } catch (error) {
    await shutdown();
    throw error;
  }

  const activePage = page;
  if (activePage === undefined) throw new Error("The seed page failed to open.");

  return {
    async capabilities() {
      return activePage.evaluate(() => globalThis.__seed!.capabilities());
    },

    async encodeClip(request) {
      const wire = await activePage.evaluate(
        (payload: ClipEncodeRequest) => globalThis.__seed!.encodeClip(payload),
        request,
      );
      return unpackClip(wire);
    },

    async renderChannelArt(request) {
      const wire = await activePage.evaluate(
        (payload: ChannelArtRequest) => globalThis.__seed!.renderChannelArt(payload),
        request,
      );
      return {
        avatarJpeg: fromBase64(wire.avatarJpeg),
        bannerJpeg: fromBase64(wire.bannerJpeg),
      };
    },

    async renderPosterCard(request) {
      const wire = await activePage.evaluate(
        (payload: PosterRequest) => globalThis.__seed!.renderPosterCard(payload),
        request,
      );
      return fromBase64(wire);
    },

    close: shutdown,
  };
}

/* ============================================================= unpack == */

function unpackClip(wire: ClipEncodeResult): ClipEncoding {
  return {
    family: wire.family,
    renditions: wire.rungs.map(unpackRendition),
    audio:
      wire.audio === null
        ? null
        : {
            track: unpackTrack(wire.audio.track),
            segments: wire.audio.segments.map(unpackSegment),
          },
    preview: unpackRendition(wire.preview),
    posterJpeg: fromBase64(wire.posterJpeg),
    framesDecoded: wire.framesDecoded,
    elapsedMs: wire.elapsedMs,
  };
}

function unpackRendition(wire: WireRungOutput): EncodedRendition {
  return {
    rung: {
      name: wire.rung.name,
      width: wire.rung.width,
      height: wire.rung.height,
      bitrate: wire.rung.bitrate,
      codec: wire.rung.codec,
    },
    track: unpackTrack(wire.track),
    segments: wire.segments.map(unpackSegment),
  };
}

function unpackTrack(wire: WireTrack): TrackConfig {
  return {
    kind: wire.kind,
    codec: wire.codec,
    ...(wire.description === null ? {} : { description: fromBase64(wire.description) }),
    timescale: wire.timescale,
    ...(wire.width === undefined ? {} : { width: wire.width }),
    ...(wire.height === undefined ? {} : { height: wire.height }),
    ...(wire.sampleRate === undefined ? {} : { sampleRate: wire.sampleRate }),
    ...(wire.channelCount === undefined ? {} : { channelCount: wire.channelCount }),
  };
}

/**
 * Split a segment's concatenated payload back into samples.
 *
 * The offsets are walked from the size table rather than recomputed, and the
 * total is checked at the end. A silent mismatch here would produce an `mdat`
 * whose sample sizes disagree with its bytes — a file that parses, appends to a
 * `SourceBuffer` without complaint, and decodes as garbage.
 */
function unpackSegment(wire: WireSegment): EncodedSegment {
  const bytes = fromBase64(wire.data);
  const samples: EncodedSample[] = [];
  let offset = 0;

  for (const sample of wire.samples) {
    samples.push({
      // `slice`, not `subarray`: these outlive the concatenated buffer and are
      // handed to the muxer, which writes them into an `mdat` — a view keeping
      // the whole segment alive per sample is a needless retention, and a view
      // is also mutable through its parent.
      data: bytes.slice(offset, offset + sample.size),
      timestampUs: sample.timestampUs,
      durationUs: sample.durationUs,
      isKeyFrame: sample.key,
      compositionOffsetUs: 0,
    });
    offset += sample.size;
  }

  if (offset !== bytes.byteLength) {
    throw new Error(
      `Segment ${wire.rung}/${wire.index} declared ${offset} bytes of samples but ` +
        `carried ${bytes.byteLength}. The base64 transfer lost or gained data.`,
    );
  }

  return {
    index: wire.index,
    startUs: wire.startUs,
    durationUs: wire.durationUs,
    samples,
  };
}

function fromBase64(value: string): Uint8Array {
  return new Uint8Array(Buffer.from(value, "base64"));
}

/* ============================================================ requests == */

/** Build the page's request for one clip, so the shape lives in one place. */
export function clipRequest(options: {
  readonly spec: ClipSpec;
  readonly ladderRungs: number;
  readonly posterAtSeconds: number;
  readonly posterWidth: number;
  readonly posterHeight: number;
  readonly previewStartSeconds: number;
  readonly previewSeconds: number;
}): ClipEncodeRequest {
  return {
    spec: options.spec,
    ladderRungs: options.ladderRungs,
    poster: {
      atSeconds: options.posterAtSeconds,
      width: options.posterWidth,
      height: options.posterHeight,
    },
    preview: {
      startSeconds: options.previewStartSeconds,
      durationSeconds: options.previewSeconds,
    },
  };
}

export type { ChannelArtRequest, ClipEncodeRequest, Palette, PosterRequest };
