/**
 * The browser half of the seed.
 *
 * Everything in this file runs inside headless Chromium, on a page served from
 * `http://127.0.0.1` so that `VideoEncoder` exists at all (research/01 §4.1).
 * It publishes one object on `window` and does nothing on its own; the driver
 * in `scripts/seed/generate-clips.ts` calls into it once per clip.
 *
 * ## The rule this file exists to keep
 *
 * The seed corpus is generated by running the **real** encode path, not by
 * writing plausible fixtures. That is what stops `src/media/encode` and
 * `src/media/muxer` from rotting: if the ladder selection, the codec
 * negotiation, the keyframe gate or the backpressure loop breaks, `pnpm seed`
 * stops producing a corpus, loudly, rather than a fixture layer continuing to
 * hand the application bytes nobody generated. So `selectLadder`,
 * `negotiateLadder` and `transcode` below are imported from `src/`, unchanged
 * and unwrapped, and the only thing this file supplies that they do not already
 * have is a `FrameSource` that draws instead of decoding.
 *
 * ## Why the results cross the boundary as base64
 *
 * Playwright's `evaluate` serialises its return value through a JSON-shaped
 * channel that does not carry `ArrayBuffer` or a typed array — a `Uint8Array`
 * arrives on the Node side as `{"0":31,"1":75,…}`, which is both wrong and
 * enormous. Base64 costs 33% on a transfer that never leaves the machine, and
 * it is unambiguous. Samples within one segment are concatenated into a single
 * string with a length table beside them, rather than one string per frame: a
 * six-second clip is ~180 frames per rung, and 180 short base64 strings carry
 * more JSON punctuation than payload.
 */

import { negotiateLadder, type CodecFamily } from "@/media/encode/capabilities";
import { SEGMENT_DURATION_US, selectLadder } from "@/media/encode/ladder";
import { transcode, type TranscodeSegment } from "@/media/encode/transcode";
import type { EncodedSample, LadderRung, TrackConfig } from "@/media/types";

import type { ClipSpec, Palette } from "../corpus";
import {
  encodeClipAudio,
  groupAudioSegments,
  renderAvatar,
  renderBanner,
  renderPoster,
  syntheticFrameSource,
} from "../synthesise";

/* ============================================================== wire == */

/** One encoded frame's place inside a segment's concatenated payload. */
export interface WireSample {
  readonly size: number;
  readonly timestampUs: number;
  readonly durationUs: number;
  readonly key: boolean;
}

export interface WireSegment {
  readonly rung: string;
  readonly index: number;
  readonly startUs: number;
  readonly durationUs: number;
  /** Base64 of every sample's bytes, in order, concatenated. */
  readonly data: string;
  readonly samples: readonly WireSample[];
}

export interface WireTrack {
  readonly kind: "video" | "audio";
  readonly codec: string;
  /** Base64 `avcC`/`esds` payload, or `null` when the encoder emitted none. */
  readonly description: string | null;
  readonly timescale: number;
  readonly width?: number;
  readonly height?: number;
  readonly sampleRate?: number;
  readonly channelCount?: number;
}

export interface WireRung {
  readonly name: string;
  readonly width: number;
  readonly height: number;
  readonly bitrate: number;
  readonly codec: string;
}

export interface ClipEncodeRequest {
  readonly spec: ClipSpec;
  /** How many rungs off the top of `selectLadder`'s answer to keep. */
  readonly ladderRungs: number;
  readonly poster: {
    readonly atSeconds: number;
    readonly width: number;
    readonly height: number;
  };
  readonly preview: {
    readonly startSeconds: number;
    readonly durationSeconds: number;
  };
}

export interface WireRungOutput {
  readonly rung: WireRung;
  readonly track: WireTrack;
  readonly segments: readonly WireSegment[];
}

export interface ClipEncodeResult {
  readonly family: string;
  readonly rungs: readonly WireRungOutput[];
  readonly audio: { readonly track: WireTrack; readonly segments: readonly WireSegment[] } | null;
  readonly preview: WireRungOutput;
  readonly posterJpeg: string;
  readonly framesDecoded: number;
  readonly elapsedMs: number;
  readonly segmentDurationUs: number;
}

export interface ChannelArtRequest {
  readonly name: string;
  readonly monogram: string;
  readonly palette: Palette;
}

export interface ChannelArtResult {
  readonly avatarJpeg: string;
  readonly bannerJpeg: string;
}

export interface PosterRequest {
  readonly spec: ClipSpec;
  readonly atSeconds: number;
  readonly width: number;
  readonly height: number;
}

export interface SeedBridge {
  encodeClip(request: ClipEncodeRequest): Promise<ClipEncodeResult>;
  renderChannelArt(request: ChannelArtRequest): Promise<ChannelArtResult>;
  /**
   * A poster on its own, with no encode behind it.
   *
   * `pnpm seed:demo` needs one: it stores a fetched Creative Commons film
   * untouched, and pulling a frame out of that file would need the MP4/WebM
   * demuxer research/01 §9.2 explains this repository deliberately does not
   * carry. So the demo videos get an honest generated card rather than a still
   * they cannot produce — and the description says so.
   */
  renderPosterCard(request: PosterRequest): Promise<string>;
  capabilities(): Promise<Record<string, unknown>>;
}

declare global {
  // `var`, not `const`: an ambient declaration on `globalThis` has to be a
  // `var` for TypeScript to widen `globalThis` at all, which is what lets the
  // Node driver write `globalThis.__seed!.encodeClip(…)` inside an `evaluate`
  // callback and have it type-check against the same interface the page
  // implements. Both halves of the bridge are then checked against one type.
  var __seed: SeedBridge | undefined;
}

/* ============================================================ encode == */

/**
 * Encode one clip: the ladder, the audio, the poster frame and the preview.
 *
 * Four passes over the same synthesised material rather than one, and the split
 * is deliberate. The ladder pass and the preview pass have different
 * *timelines* — the preview is a window out of the middle of the clip and must
 * start at its own t=0 so it plays standalone — so folding them into one
 * `transcode` call would mean a source that emits a discontinuous timeline,
 * which the keyframe gate in `ladder.ts` correctly treats as a segment boundary
 * and which would put a spurious cut in the middle of the full ladder.
 */
async function encodeClip(request: ClipEncodeRequest): Promise<ClipEncodeResult> {
  const { spec } = request;
  const startedAt = performance.now();

  const shapes = selectLadder({ width: spec.width, height: spec.height }).slice(
    0,
    Math.max(1, request.ladderRungs),
  );
  const ladder = await negotiateLadder({ shapes, frameRate: spec.frameRate });

  const ladderOutput = await encodeLadder(spec, ladder.rungs, ladder.family, {});

  // The preview rides the ladder's *lowest* rung, so it shares an encoder
  // configuration with something the player already serves rather than
  // introducing a resolution nothing else in the corpus uses.
  const previewRung = ladder.rungs[ladder.rungs.length - 1]!;
  const preview = await encodeLadder(spec, [previewRung], ladder.family, {
    startSeconds: request.preview.startSeconds,
    durationSeconds: request.preview.durationSeconds,
  });
  const previewOutput = preview[0];
  if (previewOutput === undefined) {
    throw new Error(`The preview pass for "${spec.caption}" produced no rendition.`);
  }

  const audio = await encodeClipAudio(spec.audio, spec.durationSeconds);
  const poster = await renderPoster(
    spec,
    request.poster.atSeconds,
    request.poster.width,
    request.poster.height,
  );

  const framesDecoded = ladderOutput.reduce(
    (total, rung) =>
      Math.max(
        total,
        rung.segments.reduce((count, segment) => count + segment.samples.length, 0),
      ),
    0,
  );

  return {
    family: ladder.family,
    rungs: ladderOutput,
    audio:
      audio === null
        ? null
        : {
            track: packTrack(audio.track),
            segments: groupAudioSegments(audio.samples).map((group) =>
              packSegment("audio", group.index, group.startUs, group.durationUs, group.samples),
            ),
          },
    preview: previewOutput,
    posterJpeg: toBase64(poster),
    framesDecoded,
    elapsedMs: Math.round(performance.now() - startedAt),
    segmentDurationUs: SEGMENT_DURATION_US,
  };
}

/**
 * One `transcode` run, collected per rung.
 *
 * `transcode` interleaves segments from every rung as they finish, so the sink
 * files them by rung name here rather than assuming an order. That is not
 * defensive: the rungs genuinely finish at different times because a 240p frame
 * encodes faster than a 360p one, and code that assumed otherwise would work on
 * a one-rung ladder and scramble on a two-rung one.
 */
async function encodeLadder(
  spec: ClipSpec,
  rungs: readonly LadderRung[],
  family: CodecFamily,
  window: { startSeconds?: number; durationSeconds?: number },
): Promise<WireRungOutput[]> {
  const tracks = new Map<string, TrackConfig>();
  const segments = new Map<string, WireSegment[]>();

  await transcode({
    source: syntheticFrameSource(spec, window),
    ladder: { family, rungs, dropped: [] },
    sink: {
      track: ({ rung, track }) => {
        tracks.set(rung.name, track);
      },
      segment: (segment: TranscodeSegment) => {
        const bucket = segments.get(segment.rung) ?? [];
        bucket.push(
          packSegment(
            segment.rung,
            segment.index,
            segment.startUs,
            segment.durationUs,
            segment.samples,
          ),
        );
        segments.set(segment.rung, bucket);
      },
      progress: () => {
        /* The driver reports progress per clip; per-frame progress would be
           thousands of `postMessage`-equivalent round trips for one log line. */
      },
    },
  });

  const output: WireRungOutput[] = [];
  for (const rung of rungs) {
    const track = tracks.get(rung.name);
    const rungSegments = segments.get(rung.name);
    if (!track || !rungSegments || rungSegments.length === 0) {
      throw new Error(
        `The ${rung.name} rung of "${spec.caption}" produced no segments. ` +
          "An encoder that configures and emits nothing is usually an " +
          "unsupported config that isConfigSupported approved (research/01 §5).",
      );
    }
    output.push({
      rung: {
        name: rung.name,
        width: rung.width,
        height: rung.height,
        bitrate: rung.bitrate,
        codec: rung.codec,
      },
      track: packTrack(track),
      segments: rungSegments.sort((a, b) => a.index - b.index),
    });
  }
  return output;
}

/* ============================================================== pack == */

function packSegment(
  rung: string,
  index: number,
  startUs: number,
  durationUs: number,
  samples: readonly EncodedSample[],
): WireSegment {
  let total = 0;
  for (const sample of samples) total += sample.data.byteLength;

  const joined = new Uint8Array(total);
  const table: WireSample[] = [];
  let offset = 0;
  for (const sample of samples) {
    joined.set(sample.data, offset);
    offset += sample.data.byteLength;
    table.push({
      size: sample.data.byteLength,
      timestampUs: sample.timestampUs,
      durationUs: sample.durationUs,
      key: sample.isKeyFrame,
    });
  }

  return { rung, index, startUs, durationUs, data: toBase64(joined), samples: table };
}

function packTrack(track: TrackConfig): WireTrack {
  return {
    kind: track.kind,
    codec: track.codec,
    description: track.description ? toBase64(track.description) : null,
    timescale: track.timescale,
    ...(track.width === undefined ? {} : { width: track.width }),
    ...(track.height === undefined ? {} : { height: track.height }),
    ...(track.sampleRate === undefined ? {} : { sampleRate: track.sampleRate }),
    ...(track.channelCount === undefined ? {} : { channelCount: track.channelCount }),
  };
}

/**
 * Bytes to base64, in chunks.
 *
 * `String.fromCharCode(...bytes)` is the one-liner and it throws
 * `RangeError: Maximum call stack size exceeded` somewhere above 100 kB of
 * arguments — a segment of 360p video is comfortably past that, so the
 * one-liner works on the first test clip and fails on the corpus. 32 kB per
 * call is well inside every engine's argument limit.
 */
function toBase64(bytes: Uint8Array): string {
  const CHUNK = 0x8000;
  let binary = "";
  for (let offset = 0; offset < bytes.length; offset += CHUNK) {
    binary += String.fromCharCode(...bytes.subarray(offset, offset + CHUNK));
  }
  return btoa(binary);
}

/* ============================================================== bridge == */

async function capabilities(): Promise<Record<string, unknown>> {
  const probe = async (codec: string): Promise<boolean> => {
    if (typeof VideoEncoder === "undefined") return false;
    try {
      const result = await VideoEncoder.isConfigSupported({
        codec,
        width: 640,
        height: 360,
        bitrate: 800_000,
        framerate: 30,
        hardwareAcceleration: "no-preference",
      });
      return result.supported === true;
    } catch {
      return false;
    }
  };

  return {
    secureContext: globalThis.isSecureContext,
    videoEncoder: typeof VideoEncoder,
    audioEncoder: typeof AudioEncoder,
    offscreenCanvas: typeof OffscreenCanvas,
    avcHigh: await probe("avc1.64001e"),
    avcBaseline: await probe("avc1.42001e"),
    userAgent: navigator.userAgent,
  };
}

globalThis.__seed = {
  encodeClip,
  async renderChannelArt(request) {
    const art = { name: request.name, monogram: request.monogram, palette: request.palette };
    return {
      avatarJpeg: toBase64(await renderAvatar(art)),
      bannerJpeg: toBase64(await renderBanner(art)),
    };
  },
  async renderPosterCard(request) {
    return toBase64(
      await renderPoster(request.spec, request.atSeconds, request.width, request.height),
    );
  },
  capabilities,
};

const status = document.getElementById("status");
if (status) status.textContent = "ready";
