// @vitest-environment node
import { describe, expect, it } from "vitest";

import { buildLadderMaster, buildMediaPlaylist } from "../../packager";
import type { LadderRung } from "../../types";
import {
  HlsParseError,
  defaultRenditionFor,
  parseMasterPlaylist,
  parseMediaPlaylist,
  resolveUri,
  segmentIndexAt,
} from "../playlist";

/**
 * The fixtures here are **generated by `src/media/packager`**, not hand-written.
 *
 * A hand-written fixture is a snapshot of what the emitter looked like on the day
 * someone typed it, and it drifts silently: the emitter gains an attribute, the
 * parser is never taught to read it, and the suite stays green because the
 * fixture still describes the old file. Generating means the parser is tested
 * against what the packager emits *today*, and a change to either side that the
 * other has not absorbed fails here.
 *
 * The two modules share no code — the emitter formats from RFC 8216 §4 and the
 * parser reads from it independently — so a round trip is a real check rather
 * than a tautology.
 *
 * The hand-written playlists appear only in the malformed-input section, where
 * the whole point is text the packager cannot produce.
 */

const LADDER: readonly LadderRung[] = [
  { name: "360p", width: 640, height: 360, bitrate: 800_000, codec: "avc1.64001e" },
  { name: "720p", width: 1280, height: 720, bitrate: 2_800_000, codec: "avc1.64001f" },
  { name: "1080p", width: 1920, height: 1080, bitrate: 5_000_000, codec: "avc1.640028" },
];

const MASTER_URL = "/api/media/videos/v1/master.m3u8";

function ladderMaster(): string {
  return buildLadderMaster({
    variants: LADDER.map((rung) => ({
      rung,
      uri: `${rung.name}/index.m3u8`,
      frameRate: 30,
      averageBandwidth: rung.bitrate,
      bandwidth: Math.round(rung.bitrate * 1.06),
    })),
    audio: {
      groupId: "aac-stereo",
      name: "English",
      uri: "audio/index.m3u8",
      codec: "mp4a.40.2",
      channels: "2",
      language: "en",
      bitrate: 128_000,
    },
    subtitles: {
      groupId: "subs",
      renditions: [
        {
          type: "SUBTITLES",
          groupId: "subs",
          name: "English",
          language: "en",
          isDefault: true,
          uri: "subs/en/index.m3u8",
        },
      ],
    },
  });
}

/** Twelve 2s segments and a short tail, which is what a 25.4s upload produces. */
function renditionPlaylist(count = 12, tail = 1.4): string {
  const segments = Array.from({ length: count }, (_, index) => ({
    uri: `seg-${String(index).padStart(5, "0")}.m4s`,
    durationSeconds: 2,
  }));
  segments.push({ uri: `seg-${String(count).padStart(5, "0")}.m4s`, durationSeconds: tail });
  return buildMediaPlaylist({ segments, initSegmentUri: "init.mp4", playlistType: "VOD" });
}

/* ----------------------------------------------------- master, round trip -- */

describe("the master playlist our packager emits", () => {
  it("reads back every variant with its bandwidth, resolution and codecs", () => {
    const master = parseMasterPlaylist(ladderMaster(), MASTER_URL);

    expect(master.version).toBe(6);
    expect(master.independentSegments).toBe(true);
    expect(master.variants).toHaveLength(3);

    const top = master.variants[2];
    expect(top?.resolution).toEqual({ width: 1920, height: 1080 });
    expect(top?.bandwidth).toBe(Math.round(5_000_000 * 1.06) + 128_000);
    expect(top?.averageBandwidth).toBe(5_000_000 + 128_000);
    expect(top?.frameRate).toBe(30);
    expect(top?.audioGroupId).toBe("aac-stereo");
    expect(top?.subtitlesGroupId).toBe("subs");
  });

  it("splits CODECS on the comma inside its quoted-string, not around it", () => {
    // `CODECS="avc1.640028,mp4a.40.2"` is one attribute containing a comma. A
    // naive split produces two unusable half-codecs, both of which fail
    // isTypeSupported, and the whole ladder disappears for a parsing reason that
    // reads as a codec problem.
    const master = parseMasterPlaylist(ladderMaster(), MASTER_URL);
    // Each rung carries its own AVC level, which is exactly why research §3 says
    // to treat "the codec string differs at all" as the `changeType` trigger.
    expect(master.variants.map((variant) => variant.codecs)).toEqual([
      ["avc1.64001e", "mp4a.40.2"],
      ["avc1.64001f", "mp4a.40.2"],
      ["avc1.640028", "mp4a.40.2"],
    ]);
  });

  it("sorts variants ascending by bandwidth, which is the order ABR wants", () => {
    const shuffled = buildLadderMaster({
      variants: [
        { rung: LADDER[2] as LadderRung, uri: "1080p/index.m3u8" },
        { rung: LADDER[0] as LadderRung, uri: "360p/index.m3u8" },
        { rung: LADDER[1] as LadderRung, uri: "720p/index.m3u8" },
      ],
    });
    const bandwidths = parseMasterPlaylist(shuffled, MASTER_URL).variants.map(
      (variant) => variant.bandwidth,
    );
    expect(bandwidths).toEqual([...bandwidths].sort((a, b) => a - b));
    expect(bandwidths).toEqual([800_000, 2_800_000, 5_000_000]);
  });

  it("resolves each variant URI against the master's own location", () => {
    const master = parseMasterPlaylist(ladderMaster(), MASTER_URL);
    expect(master.variants.map((variant) => variant.uri)).toEqual([
      "/api/media/videos/v1/360p/index.m3u8",
      "/api/media/videos/v1/720p/index.m3u8",
      "/api/media/videos/v1/1080p/index.m3u8",
    ]);
  });

  it("reads the audio and subtitle groups, and finds the default audio rendition", () => {
    const master = parseMasterPlaylist(ladderMaster(), MASTER_URL);
    expect(master.renditions).toHaveLength(2);

    const audio = defaultRenditionFor(master, "AUDIO", "aac-stereo");
    expect(audio?.uri).toBe("/api/media/videos/v1/audio/index.m3u8");
    expect(audio?.channels).toBe("2");
    expect(audio?.language).toBe("en");
    expect(audio?.isDefault).toBe(true);
    expect(audio?.autoselect).toBe(true);

    const subtitles = defaultRenditionFor(master, "SUBTITLES", "subs");
    expect(subtitles?.uri).toBe("/api/media/videos/v1/subs/en/index.m3u8");
  });

  it("returns nothing for a group a variant does not reference", () => {
    const master = parseMasterPlaylist(ladderMaster(), MASTER_URL);
    expect(defaultRenditionFor(master, "AUDIO", undefined)).toBeUndefined();
  });

  it("parses without a base, leaving URIs relative for a caller that resolves its own", () => {
    const master = parseMasterPlaylist(ladderMaster());
    expect(master.variants[0]?.uri).toBe("360p/index.m3u8");
  });
});

/* ------------------------------------------------------ media, round trip -- */

describe("the media playlist our packager emits", () => {
  it("reads every segment with a start time summed from the EXTINFs", () => {
    const playlist = parseMediaPlaylist(
      renditionPlaylist(),
      "/api/media/videos/v1/720p/index.m3u8",
    );

    expect(playlist.version).toBe(6);
    expect(playlist.playlistType).toBe("VOD");
    expect(playlist.endList).toBe(true);
    expect(playlist.targetDurationSeconds).toBe(2);
    expect(playlist.initSegmentUri).toBe("/api/media/videos/v1/720p/init.mp4");
    expect(playlist.segments).toHaveLength(13);

    expect(playlist.segments[0]).toMatchObject({
      index: 0,
      uri: "/api/media/videos/v1/720p/seg-00000.m4s",
      durationSeconds: 2,
      startSeconds: 0,
    });
    expect(playlist.segments[5]?.startSeconds).toBeCloseTo(10, 9);
    expect(playlist.totalDurationSeconds).toBeCloseTo(25.4, 9);
  });

  it("recognises a fixed segment grid with a short final segment as uniform", () => {
    // A VOD asset almost never divides evenly into 2s, so treating a short tail
    // as irregular would throw away the O(1) seek lookup on essentially every
    // real video.
    const playlist = parseMediaPlaylist(renditionPlaylist(), "/x/index.m3u8");
    expect(playlist.uniformSegmentDurationSeconds).toBe(2);
  });

  it("declares a genuinely irregular list non-uniform rather than guessing", () => {
    const text = buildMediaPlaylist({
      segments: [
        { uri: "a.m4s", durationSeconds: 2 },
        { uri: "b.m4s", durationSeconds: 3.5 },
        { uri: "c.m4s", durationSeconds: 2 },
      ],
      initSegmentUri: "init.mp4",
    });
    const playlist = parseMediaPlaylist(text, "/x/index.m3u8");
    expect(playlist.uniformSegmentDurationSeconds).toBeNull();
    // …and the scan fallback still answers correctly.
    expect(segmentIndexAt(playlist, 0)).toBe(0);
    expect(segmentIndexAt(playlist, 2.5)).toBe(1);
    expect(segmentIndexAt(playlist, 5.6)).toBe(2);
  });

  it("keeps EXT-X-MAP off a WebVTT playlist and does not demand one", () => {
    // The emitter omits EXT-X-MAP for subtitles, whose segments are plain text.
    // The parser must not read that as the missing-init-segment fault.
    const text = buildMediaPlaylist({
      segments: [{ uri: "seg-00000.vtt", durationSeconds: 6 }],
      playlistType: "VOD",
    });
    const playlist = parseMediaPlaylist(text, "/subs/en/index.m3u8");
    expect(playlist.initSegmentUri).toBeUndefined();
    expect(playlist.segments[0]?.uri).toBe("/subs/en/seg-00000.vtt");
  });

  it("carries an EXTINF title across, and treats an empty one as absent", () => {
    const withTitle = parseMediaPlaylist(
      buildMediaPlaylist({
        segments: [{ uri: "a.m4s", durationSeconds: 2, title: "chapter one" }],
        initSegmentUri: "init.mp4",
      }),
    );
    expect(withTitle.segments[0]?.title).toBe("chapter one");

    const withoutTitle = parseMediaPlaylist(renditionPlaylist(1, 1));
    expect(withoutTitle.segments[0]?.title).toBeUndefined();
  });

  it("reads a playlist that is still growing, with no EXT-X-ENDLIST", () => {
    const text = buildMediaPlaylist({
      segments: [{ uri: "a.m4s", durationSeconds: 2 }],
      initSegmentUri: "init.mp4",
      endList: false,
    });
    expect(parseMediaPlaylist(text).endList).toBe(false);
  });
});

/* --------------------------------------------------------- segment lookup -- */

describe("segmentIndexAt", () => {
  const playlist = parseMediaPlaylist(renditionPlaylist(), "/x/index.m3u8");

  it("divides rather than searches, because every segment is the same length", () => {
    expect(segmentIndexAt(playlist, 0)).toBe(0);
    expect(segmentIndexAt(playlist, 1.999)).toBe(0);
    expect(segmentIndexAt(playlist, 2)).toBe(1);
    expect(segmentIndexAt(playlist, 17.3)).toBe(8);
  });

  it("lands the short final segment on the last index, not past it", () => {
    expect(segmentIndexAt(playlist, 24)).toBe(12);
    expect(segmentIndexAt(playlist, 25.399)).toBe(12);
  });

  it("answers null outside the asset rather than clamping silently", () => {
    // The seek path clamps deliberately and visibly; a parser that clamped here
    // would make "seek past the end" indistinguishable from "seek to the end".
    expect(segmentIndexAt(playlist, 25.4)).toBeNull();
    expect(segmentIndexAt(playlist, 99)).toBeNull();
    expect(segmentIndexAt(playlist, -1)).toBeNull();
    expect(segmentIndexAt(playlist, Number.NaN)).toBeNull();
  });
});

/* ------------------------------------------------------------- resolveUri -- */

describe("resolveUri", () => {
  it("resolves a sibling against a root-relative playlist URL", () => {
    expect(resolveUri("seg-00001.m4s", "/api/media/videos/v1/720p/index.m3u8")).toBe(
      "/api/media/videos/v1/720p/seg-00001.m4s",
    );
  });

  it("resolves against an absolute base, which is the CDN deployment", () => {
    expect(resolveUri("seg-00001.m4s", "https://media.example/videos/v1/720p/index.m3u8")).toBe(
      "https://media.example/videos/v1/720p/seg-00001.m4s",
    );
  });

  it("keeps a bare-relative base bare rather than rooting it", () => {
    expect(resolveUri("seg.m4s", "videos/v1/720p/index.m3u8")).toBe(
      "videos/v1/720p/seg.m4s",
    );
  });

  it("leaves an already-absolute URI alone, which is how a rung points at a CDN", () => {
    expect(resolveUri("https://cdn.example/a.m4s", "/api/media/v1/index.m3u8")).toBe(
      "https://cdn.example/a.m4s",
    );
  });

  it("returns the URI untouched when there is no base", () => {
    expect(resolveUri("a.m4s", undefined)).toBe("a.m4s");
  });
});

/* ------------------------------------------------------------- malformed -- */

describe("malformed input", () => {
  it("refuses a file that does not start with #EXTM3U", () => {
    // The realistic version of this is an error page served with a 200 status,
    // which every later check would blame on something else.
    expect(() => parseMediaPlaylist("<!doctype html>\n<html>…")).toThrow(HlsParseError);
    expect(() => parseMediaPlaylist("<!doctype html>")).toThrow(/must begin with #EXTM3U/);
  });

  it("refuses a truncated playlist whose last EXTINF has no URI", () => {
    // A partial write, or a proxy that cut the response short. The dangerous
    // reading is the lenient one: dropping the orphan EXTINF produces a playlist
    // that parses, plays, and ends early with no error anywhere.
    // Drop the final segment URI, the ENDLIST and the terminator, leaving an
    // EXTINF with nothing after it — the shape a half-written file really has.
    const truncated = renditionPlaylist().split("\n").slice(0, -3).join("\n");
    expect(() => parseMediaPlaylist(truncated)).toThrow(/#EXTINF that has no URI/);
  });

  it("refuses an fMP4 playlist with no EXT-X-MAP", () => {
    const withoutMap = renditionPlaylist().replace(/#EXT-X-MAP:[^\n]*\n/, "");
    expect(() => parseMediaPlaylist(withoutMap)).toThrow(/no #EXT-X-MAP/);
  });

  it("refuses a media playlist with no EXT-X-TARGETDURATION", () => {
    const without = renditionPlaylist().replace(/#EXT-X-TARGETDURATION:[^\n]*\n/, "");
    expect(() => parseMediaPlaylist(without)).toThrow(/EXT-X-TARGETDURATION is REQUIRED/);
  });

  it("refuses a media playlist with no segments", () => {
    expect(() => parseMediaPlaylist("#EXTM3U\n#EXT-X-TARGETDURATION:2\n")).toThrow(
      /at least one segment/,
    );
  });

  it("refuses an EXTINF with no comma, and one whose duration is not a number", () => {
    const base = "#EXTM3U\n#EXT-X-TARGETDURATION:2\n#EXT-X-MAP:URI=\"init.mp4\"\n";
    expect(() => parseMediaPlaylist(`${base}#EXTINF:2\na.m4s\n`)).toThrow(/no comma/);
    expect(() => parseMediaPlaylist(`${base}#EXTINF:soon,\na.m4s\n`)).toThrow(
      /is not a non-negative number/,
    );
  });

  it("ignores an unknown tag, and records that it saw one", () => {
    // RFC 8216 §4.1 requires clients to ignore unrecognized tags. Recording them
    // is the difference between a packager that starts emitting something new
    // being visible to a test and being invisible until a user reports it.
    const withExtra = renditionPlaylist().replace(
      "#EXT-X-TARGETDURATION:2",
      "#EXT-X-TARGETDURATION:2\n#EXT-X-FUTURE-THING:42",
    );
    const playlist = parseMediaPlaylist(withExtra);
    expect(playlist.unknownTags).toContain("EXT-X-FUTURE-THING");
    expect(playlist.segments).toHaveLength(13);
  });

  it("ignores a tag we know about, and does not report it as unknown", () => {
    // The distinction is the point: `unknownTags` has to mean "our packager
    // emitted something nobody taught the parser about". A list that also
    // collects every deliberately-skipped tag can never be asserted on.
    const withSequence = renditionPlaylist().replace(
      "#EXT-X-TARGETDURATION:2",
      "#EXT-X-TARGETDURATION:2\n#EXT-X-MEDIA-SEQUENCE:0",
    );
    const playlist = parseMediaPlaylist(withSequence);
    expect(playlist.unknownTags).toEqual([]);
    expect(playlist.segments).toHaveLength(13);
  });

  it("reports nothing unknown for the playlists our own packager writes", () => {
    // The regression check the field exists for, in both directions.
    expect(parseMediaPlaylist(renditionPlaylist()).unknownTags).toEqual([]);
    expect(parseMasterPlaylist(ladderMaster(), MASTER_URL).unknownTags).toEqual([]);
  });

  it.each([
    ["#EXT-X-KEY:METHOD=AES-128,URI=\"k.bin\"", /encrypted/],
    ["#EXT-X-BYTERANGE:1024@0", /slice of a larger resource/],
    ["#EXT-X-DISCONTINUITY", /timeline restarts/],
    ["#EXT-X-DEFINE:NAME=\"host\",VALUE=\"cdn\"", /substitutions/],
    ["#EXT-X-PART:DURATION=0.5,URI=\"p.m4s\"", /low-latency/],
  ])("refuses %s rather than ignoring it into a silent failure", (tag, message) => {
    // These are the opposite case from an unknown tag: ignoring one produces a
    // player that runs and is wrong — ciphertext appended to a decoder, a
    // `{$host}` literal fetched as a path, a timeline that restarts underneath a
    // buffer we are appending into.
    const withTag = renditionPlaylist().replace(
      "#EXT-X-TARGETDURATION:2",
      `#EXT-X-TARGETDURATION:2\n${tag}`,
    );
    expect(() => parseMediaPlaylist(withTag)).toThrow(message);
  });

  it("refuses an EXT-X-MAP that carries a BYTERANGE", () => {
    const text =
      "#EXTM3U\n#EXT-X-TARGETDURATION:2\n" +
      '#EXT-X-MAP:URI="init.mp4",BYTERANGE="720@0"\n#EXTINF:2,\na.m4s\n';
    expect(() => parseMediaPlaylist(text)).toThrow(/whole init segments/);
  });

  it("refuses a master playlist with a dangling group reference", () => {
    // The one master-playlist fault that produces silent audio rather than an
    // error: the variant plays, the group is never resolved, nothing reports why.
    const master = ladderMaster().replace(/#EXT-X-MEDIA:TYPE=AUDIO[^\n]*\n/, "");
    expect(() => parseMasterPlaylist(master, MASTER_URL)).toThrow(
      /which no #EXT-X-MEDIA declares/,
    );
  });

  it("refuses a variant with no BANDWIDTH or no CODECS", () => {
    const noBandwidth =
      '#EXTM3U\n#EXT-X-STREAM-INF:CODECS="avc1.640028",RESOLUTION=1920x1080\nv.m3u8\n';
    expect(() => parseMasterPlaylist(noBandwidth)).toThrow(/required BANDWIDTH/);

    const noCodecs = "#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1000000\nv.m3u8\n";
    expect(() => parseMasterPlaylist(noCodecs)).toThrow(/required CODECS/);
  });

  it("refuses a master playlist truncated after its last EXT-X-STREAM-INF", () => {
    const truncated = ladderMaster().split("\n").slice(0, -2).join("\n");
    expect(() => parseMasterPlaylist(truncated)).toThrow(/has no URI after it/);
  });

  it("refuses a master playlist with no variants", () => {
    expect(() => parseMasterPlaylist("#EXTM3U\n#EXT-X-VERSION:6\n")).toThrow(
      /at least one variant/,
    );
  });

  it("refuses an unterminated quoted-string and junk after a quoted value", () => {
    expect(() =>
      parseMasterPlaylist('#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1,CODECS="avc1\nv.m3u8\n'),
    ).toThrow(/Unterminated quoted-string/);
    expect(() =>
      parseMasterPlaylist('#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1,CODECS="a"x\nv.m3u8\n'),
    ).toThrow(/Junk after the quoted value/);
  });

  it("reports the line number, because that is what a bug report needs", () => {
    const text = `#EXTM3U\n#EXT-X-TARGETDURATION:2\n#EXT-X-MAP:URI="init.mp4"\n#EXTINF:2\na.m4s\n`;
    try {
      parseMediaPlaylist(text);
      expect.unreachable("should have thrown");
    } catch (error) {
      expect(error).toBeInstanceOf(HlsParseError);
      expect((error as HlsParseError).line).toBe(4);
    }
  });

  it("tolerates CRLF line endings without leaving a \\r on a segment URI", () => {
    // A \r left on a URI produces a fetch for a path that does not exist, and the
    // error blames the segment rather than the line ending.
    const crlf = renditionPlaylist().replace(/\n/g, "\r\n");
    const playlist = parseMediaPlaylist(crlf, "/x/index.m3u8");
    expect(playlist.segments[0]?.uri).toBe("/x/seg-00000.m4s");
    expect(playlist.initSegmentUri).toBe("/x/init.mp4");
  });
});
