/**
 * The map catalogue (SPEC §4.14, D40, F6).
 *
 * **This file is not a barrel.** Importing it must not pull a single board's
 * geometry into the bundle: sixteen boards are 286 KB of JSON, which would
 * dominate the initial payload, so each one is reached through its own
 * `import()` and only the selected map is ever fetched (D40). Opening the map
 * picker costs nothing but this module; choosing a map costs exactly one more
 * request.
 *
 * Every file here is generated by `pnpm run build:maps` and committed, so a
 * board's graph changes visibly in a diff (D36). See `README.md` in this
 * directory for each map's provenance and licence.
 */

import type { MapFile } from "@/engine/types";

/**
 * Per-slug loaders. Written out one by one rather than built from a template
 * because a bundler can only split a static `import()` — a computed specifier
 * would either fail to resolve or pull every board into one chunk.
 *
 * The `as unknown as MapFile` is unavoidable: TypeScript infers a JSON import's
 * literal shape, so `suit` arrives as `string` rather than the three-way union.
 * `validateMap` checks the real shape at build time (T7), which is where that
 * guarantee belongs.
 */
const LOADERS: Record<string, () => Promise<{ default: unknown }>> = {
  "classic-world": () => import("./classic-world.json"),
  "world-simple": () => import("./world-simple.json"),
  europe: () => import("./europe.json"),
  "usa-states": () => import("./usa-states.json"),
  asia: () => import("./asia.json"),
  africa: () => import("./africa.json"),
  "north-america": () => import("./north-america.json"),
  "south-america": () => import("./south-america.json"),
  "australia-new-zealand": () => import("./australia-new-zealand.json"),
  "middle-east": () => import("./middle-east.json"),
  "world-extended": () => import("./world-extended.json"),
  "napoleonic-europe": () => import("./napoleonic-europe.json"),
  tiny3: () => import("./tiny3.json"),
  tiny4: () => import("./tiny4.json"),
  mini: () => import("./mini.json"),
  quad: () => import("./quad.json"),
};

/**
 * Every shipped slug, in picker order — the only enumeration of the catalogue.
 *
 * The four fixtures are last and are listed in `FIXTURE_SLUGS` as well: they are
 * loadable (the engine suites and the end-to-end tiny map need them) but they
 * **never appear in the in-game picker** (D39). A picker shows
 * `MAP_SLUGS.filter((s) => !FIXTURE_SLUGS.includes(s))`.
 */
export const MAP_SLUGS: readonly string[] = [
  "classic-world",
  "world-simple",
  "europe",
  "usa-states",
  "asia",
  "africa",
  "north-america",
  "south-america",
  "australia-new-zealand",
  "middle-east",
  "world-extended",
  "napoleonic-europe",
  "tiny3",
  "tiny4",
  "mini",
  "quad",
];

/** The engine fixtures inside `MAP_SLUGS`. Not player-facing content (D39). */
export const FIXTURE_SLUGS: readonly string[] = ["tiny3", "tiny4", "mini", "quad"];

/** Per-slug dynamic import. Rejects on an unknown slug. */
export async function loadMapFile(slug: string): Promise<MapFile> {
  const load = LOADERS[slug];
  if (load === undefined) throw new Error(`unknown map slug: ${slug}`);
  // Not named `module`: Next's `no-assign-module-variable` rule reserves it.
  const loaded = await load();
  return loaded.default as unknown as MapFile;
}
